# Generated by Django 2.2.6 on 2019-10-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='email',
        ),
        migrations.RemoveField(
            model_name='node',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='node',
            name='last_name',
        ),
    ]
