# Generated by Django 2.2.6 on 2019-10-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191026_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyValueSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bonus',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
