# Generated by Django 2.2.6 on 2019-11-26 18:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191102_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='revert_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
