# Generated by Django 2.2.6 on 2019-10-26 17:10

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('model_path', models.CharField(help_text='Path to the model: ex: myapp.models.MyModel', max_length=200, verbose_name='Model path')),
                ('model_pk', models.PositiveSmallIntegerField(verbose_name='Root node primary key')),
            ],
            options={
                'verbose_name': 'Mptt graph',
                'verbose_name_plural': 'Mptt graphs',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='graph.TreeNode', verbose_name='Parent node')),
            ],
            options={
                'verbose_name': 'Tree node',
                'verbose_name_plural': 'Tree nodes',
                'ordering': ('title',),
            },
        ),
    ]
